### ISSUE TITLE
code

### ISSUE THREAD

**Issue by forfrees** [schafert/JSM2019Proceedings#1]
hello，I am a student in uestc, and I am learning your program. can you share your code about GuppyReinforcementLearning with me? 
Thank you in advance. My email is 202121081118@std.uestc.edu.cn

**Comment by forfrees** [comment]
and if it is not convenient, it is ok.

**Comment by schafert** [comment]
For now, all that is available is the code in the paper available online https://arxiv.org/abs/2009.04003
